# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: qrvc

builds:
  - id: unix-binary
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: windows-binary
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64


release:
  github:
    owner: ulfschneider
    name: qrvc


archives:
  # tar.gz for Linux & macOS, used by Homebrew
  - id: unix-tar
    formats: tar.gz
    ids:
      - unix-binary
    name_template: "{{ .ProjectName }}_{{ .Os | title }}_{{ .Arch }}"

  # ZIPs for Windows, used by winget
  - id: windows-zip
    formats: zip
    ids:
      - windows-binary
    name_template: "{{ .ProjectName }}_Windows_{{ .Arch }}"


homebrew_casks:
  - name: qrvc
    ids:
      - unix-tar
    binaries:
      - qrvc
    url:
      template: "https://github.com/ulfschneider/qrvc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/ulfschneider/qrvc"

    homepage: "https://github.com/ulfschneider/qrvc"
    description: "Use the command line to make a QR code from a vCard"
    license: "MIT"

    repository:
      owner: ulfschneider
      name: homebrew-tap
      branch: main

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr",
              args: ["-dr", "com.apple.quarantine", "#{staged_path}/qrvc"]
          end

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
